version: 2.1

jobs:
  validate:
    docker:
      - image: hashicorp/packer:full-1.7.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate virtualbox
          command: packer validate ./ubuntu/ubuntu-18.04-amd64.json
  build-virtualbox:
    docker:
      - image: hashicorp/packer:full-1.7.5
    working_directory: ~/ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: ~/ubuntu
      - run:
          name: Build virtualbox
          command: export PACKER_LOG=1 && packer build ./ubuntu/ubuntu-18.04-amd64.json
      - store_artifacts:
          path: manifest-virtualbox.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-virtualbox:
          requires:
            - validate
