version: 2.1

jobs:
  validate:
    docker:
      - image: hashicorp/packer:full-1.7.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate virtualbox
          command: packer validate ./ubuntu/ubuntu-18.04-amd64.json
  build-virtualbox:
    docker:
      - image: cimg/base:2021.07
    working_directory: ~/ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: ~/ubuntu
      - run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y git bash openssl curl zip build-essential dkms virtualbox virtualbox-dkms virtualbox-guest-additions-iso linux-headers-aws
          PACKER_LATEST_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/packer | jq -r -M '.current_version')
          curl -s "https://releases.hashicorp.com/packer/1.7.5/packer_1.7.5_linux_amd64.zip" --output /tmp/packer_linux_amd64.zip
          sudo unzip -o /tmp/packer_linux_amd64.zip -d /usr/local/bin/
          packer build -debug ./ubuntu/ubuntu-18.04-amd64.json
      - store_artifacts:
          path: manifest-virtualbox.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-virtualbox:
          requires:
            - validate
