version: 2.1

jobs:
  validate:
    docker:
      - image: hashicorp/packer:full-1.7.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate virtualbox
          command: packer validate ./ubuntu/ubuntu-18.04-amd64.json
  build-virtualbox:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: ~/ubuntu
          
      - run: apt-get install -y sudo
      - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
      - run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y git bash openssl curl zip build-essential linux-headers-`uname -r` dkms virtualbox virtualbox-dkms virtualbox-guest-additions-iso
          sudo apt-get install -y cpu-checker
          sudo kvm-ok
      - store_artifacts:
          path: manifest-virtualbox.json

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-virtualbox:
          requires:
            - validate
