---

name: ubuntu-virtualbox-minimal
env:
  PACKER_VERSION: 1.7.4

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/virtualbox.yml
    - ubuntu/*
    - ubuntu/*/*
    - _common/*

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      # # fix backwards incompatibilities in template
      # - name: Fix Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: fix
      #     target: ubuntu/ubuntu-18.04-amd64.json

      # validate templates
      - name: virtualbox - packer validate
        uses: docker://hashicorp/packer:latest
        with: 
          args: validate -syntax-only ubuntu/ubuntu-18.04-amd64.json
        env:
          PACKER_LOG: 1

      # build artifact
      - name: virtualbox - packer build
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y git bash openssl curl zip 
          sudo apt-get install -y build-essential linux-headers-`uname -r` dkms virtualbox virtualbox-dkms virtualbox-guest-additions-iso
          sudo apt-get install cpu-checker
          sudo kvm-ok
          packer build ubuntu/ubuntu-18.04-amd64.json
        env:
          PACKER_LOG: 0

      # additional steps to process artifacts
