---

name: ubuntu-virtualbox-minimal
env:
  PACKER_VERSION: 1.7.4

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/virtualbox.yml

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # # fix backwards incompatibilities in template
      # - name: Fix Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: fix
      #     target: ubuntu/ubuntu-18.04-amd64.json

      # validate templates
      - name: virtualbox - packer validate
        uses: actions/checkout@v2
        with:
          command: validate
          arguments: -syntax-only
          # multiple files, separated by whitespace
          target: ubuntu/ubuntu-18.04-amd64.json
        env:
          PACKER_LOG: 1

      # build artifact
      - name: virtualbox - packer build
        run: |
          sudo apt-get update
          sudo apt-get install -y git bash openssl curl zip 
          sudo add-apt-repository multiverse 
          sudo apt-get update
          sudo apt install -y virtualbox linux-headers-generic
          sudo dpkg-reconfigure virtualbox-dkms
          curl -SL https://releases.hashicorp.com/packer/$PACKER_VERSION/packer_${PACKER_VERSION}_linux_amd64.zip -o packer_linux_amd64.zip
          unzip packer_linux_amd64.zip
          ./packer build -color=false -on-error=abort ubuntu/ubuntu-18.04-amd64.json
        env:
          PACKER_LOG: 0

      # additional steps to process artifacts
